version: 2
project_name: clipboard-clearer

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    main: ./
    binary: clipboard-clearer
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=gcc
      - CGO_ENABLED=1
    flags:
      - -gccgoflags="-DDARWIN -x objective-c -fobjc-arc"
    ldflags:
      - -s -w
      - framework=Cocoa
      - framework=WebKit

  - id: linux-amd64
    main: ./
    binary: clipboard-clearer
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: windows-amd64
    main: ./
    binary: clipboard-clearer
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    builds:
      - darwin-amd64
      - linux-amd64
      - windows-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
