version: 2

project_name: clipboard-clearer

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin
    env:
      - CGO_ENABLED=1
      - CC=gcc
    goos:
      - darwin
    goarch:
      - amd64
    gcflags:
      - -DDARWIN -x objective-c -fobjc-arc
    ldflags:
      - framework=Cocoa
      - -s -w

  - id: linux
    # skip: true
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

  - id: windows
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -H=windowsgui
      - -s -w

archives:
  - id: darwin-archive
    builds:
      - darwin
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_{{ .Arch }}"
    format: tar.gz

  - id: linux-archive
    builds:
      - linux
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}"
    format: tar.gz

  - id: windows-archive
    builds:
      - windows
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}"
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
