name: CI

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Install Go packages dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libx11-dev 
          sudo apt install -y gcc libgtk-3-dev libayatana-appindicator3-dev 

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: typos-action
        uses: crate-ci/typos@a67079b4ae32e18c3f53d75368c52ce53b5fb56b # v1.35.4

  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      release: ${{ steps.go-semver.outputs.MAIN_NEW_RELEASE }}
      semver: ${{ steps.go-semver.outputs.MAIN_SEMVER }}
    needs:
      - typos
      - golangci
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up GPG key
        run: |
          mkdir -p ~/secrets
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > ~/secrets/private.asc
          GO_SEMVER_GPG_KEY_PATH="${HOME}/secrets/private.asc"
          chmod 600 "${GO_SEMVER_GPG_KEY_PATH}"
          echo "GO_SEMVER_GPG_KEY_PATH=${GO_SEMVER_GPG_KEY_PATH}" >> $GITHUB_ENV

      - name: Install Go Semver Release
        run: |
          curl -SL https://github.com/s0ders/go-semver-release/releases/latest/download/go-semver-release-linux-amd64 -o ./go-semver-release \
          && chmod +x ./go-semver-release

      - name: Go Semver Release
        id: go-semver
        env:
          GO_SEMVER_RELEASE_ACCESS_TOKEN: ${{ secrets.GO_SEMVER_RELEASE_ACCESS_TOKEN }}
        run: |
          ./go-semver-release release https://github.com/s0ders/clipboard-clearer.git \
          --branches='[{"name": "main"}]' \
          --git-name "Go Semver Release CI" \
          --git-email "39492740+s0ders@users.noreply.github.com" \
          --tag-prefix "v" \
          --gpg-key-path "${GO_SEMVER_GPG_KEY_PATH}" \
          --verbose

  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - versioning
    if: ${{needs.versioning.outputs.release == 'true'}}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable

      - name: Install Go packages dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libx11-dev 
          sudo apt install -y gcc libgtk-3-dev libayatana-appindicator3-dev 

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GO_SEMVER_RELEASE_ACCESS_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
